config/routes.rb
Onboard::Application.routes.draw do
  
  get "contents/about"
  get "contents/terms"
  get "contents/privacy"
  # to fit in with omniauth's callback urls
  get "/auth/:provider/callback" => "social_logins#create"


  # static pages
  get "/about" => "contents#about"
  get "/privacy" => "contents#privacy"
  get "/terms-and-conditions" => "contents#terms", as: "terms"

  # this is where the URLs of our pages are set
  resources   :users, paths: "signups"
  resources   :jobs

  # because I don't want to log in twice as a user
  # let's use a singular resource
  resource	  :session 	

  root "jobs#index"


end

app/models/job.rb
class Job < ActiveRecord::Base

	belongs_to :user

	validates 	:title, presence: true, length: { minimum: 5 }
	validates 	:description, presence: true
	validates 	:company_name, presence: true
	validates 	:company_tagline, presence: true
	validates 	:location, presence: true

	geocoded_by	:location
	after_validation :geocode


end

app/models/user.rb
class User < ActiveRecord::Base
	
	has_many :jobs

	# added some validations
	validates :name, presence: true, unless: :has_social_login?
	validates :username, presence: true, uniqueness: true, unless: :has_social_login?
	validates :email, presence: true, uniqueness: true, unless: :has_social_login?
	validates :password, presence: true, confirmation: true, unless: :has_social_login?

	# this is part of rails
	# 3.2 and 4.0
	# it puts our unencrypted password into our database
	# as an encryted password into password digest
	has_secure_password validations: false

	def has_social_login?
		# question mark above is just part of the name
		facebook_id.present? or twitter_id.present? or linkedin_id.present?
		
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # lets make a custom method that finds theuser in the db
  # based on the session[:user_id]


  def current_user

  	if session[:user_id].present?
  		User.find(session[:user_id])
  	end

  end

  # we want to make this available to the 
  # views as well as the controllers
  helper_method :current_user
  # right above this is a function - technically the same as current_user() 

  # let's add some authorization
  def require_user
      if current_user.nil?
          flash[:error] = "You must be a user to view this page"
          redirect_to new_user_path
      end
   end       
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def about
  end

  def terms
  end

  def privacy
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

	# the user must be signed in
	# for everything APART from the index and show
  before_action :require_user, except: [:index, :show]

  def index
      @job = Job.all
  end

  def show
    # not current_user.jobs because it can be anyone's job
    @job = Job.find(params[:id])
  end

  def new
  	# @job = Job.new
  	# because we want the job attached to a user
  	@job = current_user.jobs.new
  	# .jobs is there becuase we've defined that user has_many jobs
  end

  def create
    @job = current_user.jobs.new(job_params)
  
    if @job.save
      flash[:success] = "Job Added"
      redirect_to job_path(@job)
    else
      render :new
    end  

  end

  def edit
      @job = current_user.jobs.find(params[:id])
  end  

  def update
      @job = current_user.jobs.find(params[:id])

      if @job.update(job_params)
        flash[:success] = "Job updated"
        redirect_to job_path(@job)
      else
        render :edit
      end
  end

  def destroy
      @job = current_user.jobs.find(params[:id])
      @job.destroy
      flash[:success] = "Job deleted"
      redirect_to root_path
  end  



  def job_params
      params.require(:job).permit(
        :title, 
        :description, 
        :company_name, 
        :company_url, 
        :company_tagline,
        :location,
        :phone,
        :application_deadline,
        :salary
        )
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	# this doesn't need a variable because its a placeholder form
  end

  def create
	# find the username and pw
	# check to see if match
	# if they do log them in
	
	# make variables for verification - grab them from db
	@username = params[:session][:username]
	@password = params[:session][:password]

	# now make a new var 
	@user = User.find_by_username(@username)

	# check username and pw match
	if @user.present? and @user.authenticate(@password)		
		# give them a session
		flash[:success] = "You've logged in. Welcome #{@user.name}."
		redirect_to root_path
	else
		flash[:error] = "Log in failed"
		render :new
	end

  end	


  def destroy
  	reset_session
  	flash[:success] = "You've logged out"
  	redirect_to root_path
  end

  # This deletes the cookie from the browser

end

app/controllers/social_logins_controller.rb
class SocialLoginsController < ApplicationController

	def create
		# this is all the info back from facebook or twitter or linkedin
		@omniauth = request.env['omniauth.auth']
		@name = @omniauth["info"]["name"]
		@provider = @omniauth["provider"]
		@provider_id = @omniauth["uid"]

		# just following how omniauth works
		@email = @omniauth["info"]["email"]

		@user = User.find_by_email(@email)

		if @user.present?
			# they're already in the system
			flash[:success] = "Logged in successfully"
		else
			# add a new user
			@user = User.new
			@user.email = @email
			@user.name = @name


			@user.facebook_id = @provider_id if @provider == "facebook"
			@user.twitter_id = @provider_id if @provider == "twitter"
			@user.linkedin_id = @provider_id if @provider == "linkedin"

			@user.save

			flash[:success] = "You've signed up"
		end	

		session[:user_id] = @user.id
		redirect_to root_path
		
	end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  		@user = User.new
  end
  def create
  	  @user = User.new(user_params)

	  if @user.save
	  	flash[:success] = "You've signed up!"
	  	 
	  	# tell the browser using a cookie that I am this user
	  	session[:user_id] = @user.id

	  	redirect_to root_path
	  else
	  	render :new
	  end
  end  


  # whitelist
  def user_params
  	params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper

	def md(text)
		RDiscount.new(text).to_html.html_safe
		# simple_format(text)
	end

end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/social_logins_helper.rb
module SocialLoginsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contents/about.html.erb
<h1>Contents#about</h1>
<p>Find me in app/views/contents/about.html.erb</p>

app/views/contents/privacy.html.erb
<h1>Contents#privacy</h1>
<p>Find me in app/views/contents/privacy.html.erb</p>

app/views/contents/terms.html.erb
<h1>Contents#terms</h1>
<p>Find me in app/views/contents/terms.html.erb</p>

app/views/jobs/_form.html.erb
<%= simple_form_for @job do |f| %>

	 	<%= f.input :title %>
	 	<%= f.input :description %>

	 	<%= f.input :company_name %>
	 	<%= f.input :company_url %>
	 	<%= f.input :company_tagline %>
	 	
	 	<%= f.input :location %>
	 	<%= f.input :phone, as: :string %>
	 	<%= f.input :application_deadline %>
	 	<%= f.input :salary, :label => "Fee"%>

	 	<%= f.button :submit %>	 		 		 	
<% end %>

app/views/jobs/edit.html.erb
<div class="eight columns offset-by-two">

<h2>Edit this Job</h2>

	<%= render "form" %>

</div>

app/views/jobs/index.html.erb
<section class="nine columns bordered">


    <div class="jobslist">
      <% @job.each do |job| %>
        <div class="single_job group">

          <%= link_to job_path(job) do %>

            <%# image_tag job.company_logo.url, class: "company_logo" %>

            <div class="job_details">
              <h3><%= job.title %> </h3>
              <p><%= job.company_name %><br> <%= job.location %></p>
            </div>

            <div class="job_actions">
              <p>Salary: <%= job.salary %></p>
              <p>Added <%= job.created_at.to_date.to_formatted_s(:long) %></p>
              <p>Submit by <%= job.application_deadline %></p>
            </div>
          <% end %>


        </div>
      <% end %>

    </div>
</section>

<aside class="three columns bordered">
  <%= form_tag root_path, method: :get, class: "search_form" do |f| %>
    <%= text_field_tag :location, params[:location], { placeholder: "Location", class: "location_search" } %>
   <% end %>

  <h3>Category</h3>
    <ul>
    CATEGORY
    </ul>

  <h3>Job type</h3>
    <ul>

    JOB TYPE
    </ul>


</aside>

app/views/jobs/new.html.erb
<div class="eight columns offset-by-two">

<h2>Add a Job</h2>

	<%= render "form" %>

</div>

app/views/jobs/show.html.erb
<div class="job_show">

<div class="row">
	<div class="four columns offset-by-four">
		<h3><%= @job.title %></h3>
		<h3><%= @job.company_name %></h3>
		<h4><%= @job.location %></h4>
	</div>
</div>

<div class="row">
	<div class="eight columns offset-by-two">
		<blockquote><%= @job.company_tagline %></blockquote>

		<!-- <%= @job.description %></p> -->
		<%= md @job.description %></p>

		<p>
			Salary: <%= @job.salary %><br>
			Website: <%= @job.company_url %><br>
			Applicaition Deadline: <%= @job.application_deadline %>
		</p>
	</div>
</div>

<div class="row">
	<div class="ten columns offset-by-one">
	<div class="map" data-lat="<%= @job.latitude %>" data-long=
	"<%= @job.longitude %>">
	</div>
	</div>
</div>

<div class="row mid">
    <a href="#" class="button">Apply</a>

        <% if current_user.present? and current_user == @job.user %>
        <%= link_to "Edit", edit_job_path(@job), class: "button" %>

        <%= link_to "Delete", job_path(@job), method: :delete, class: "button", confirm: "Are you sure?" %>
    <% end %>
</div>

</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <title>Jobs</title>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <!-- below "application is the application.css MANIFEST which pulls eveything else in" -->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <header class="row">
    <h1 class="two columns">
      <%= link_to(root_path) do %>
        <%= image_tag "logo.png" %>
      <% end %>
    </h1>

    <nav class="ten columns">

      <% if current_user.present? %>
          LOGGED IN as <%= current_user.name %>
                <!--
                <%= session[:user_id] %>
                <%= User.find(session[:user_id]).name %>
                <%= current_user %>
                -->
          <%= link_to current_user.name, "#" %>
          <%= link_to "Add a job", new_job_path %>
          <%= link_to "Account", "#" %>
          <%= link_to "Log out", session_path, method: :delete %>
              
      <% else %>
      <%= link_to "Log in", new_session_path %>

      <!-- added "new_user_path" below as the destination for sign up-->
      <%= link_to "Sign up", new_user_path %>
      <% end %> 
    
    </nav>
  </header>

  <% flash.each do |key, value| %>
    <div class="twelve columns flash <%= key %>"><%= value %></div>
  <% end %>

  <article class="row">
    <%= yield %>
  </article>

  <footer>
    <p>&copy; <%= Date.today.year %> Onboard Ltd</p>
  </footer>
</div> <!--  .container -->

</body>
</html>

app/views/users/new.html.erb
<div class="eight columns offset-by-two">

<h2>Sign Up</h2>
	
	<%= simple_form_for @user do |f| %>
	 	<%= f.input :name %>
	 	<%= f.input :username %>
	 	<%= f.input :email %>
	 	<%= f.input :password %>
	 	<%= f.input :password_confirmation, label: "Confirm password" %>

	 	<%= f.button :submit %>	 		 		 	

<% end %>
</div>

<div class="six columns offset-by-three mid social">
	<span>Sign up with...</span>
	<%= link_to "Facebook", "/auth/facebook", class: "button" %>
	<%= link_to "Twitter", "/auth/twitter", class: "button" %>
	<%= link_to "LinkedIn", "/auth/linkedin", class: "button" %>
</div>